from Crypto.Util.number import bytes_to_long, long_to_bytes

# Constants from the challenge
m = 9792986822963146992114161946549377254001156012300083076259452975070903436656675903033418798369811004678022807932064872669773556983318074157606463933686225452143852071767552582367819932516654167400507310054793760473098421162463267
A = 246920531455433048826966670968977027196902794022573095007307132382393013927558904839982249967656424317118051446771969623490992917094197975459553923550187
B = 3120090466259654766880909097573553950487818021670727992039931232537173262599219376624291488340607228938989670215080876932583555412966984946786628621917436142053528648425399877486481618672307477414787846984446437445450282569184963
e = 4180488827

# Ciphertext blocks from the file comment
CT = [
    263928838896714332657762314348602240455087661491500131260179929152321790693260683004004767933801216877412896467528419672112455669506824987777448696213888416333755744665868795853306879814179767910033263080874331851322593343273834,
    7500716958005582985508201577146205078774368134456220390802616323312171951781595852608949532619393759348663684985174625019004577610546554994801687569942118260000292201829011312249563036393035204990811392856155820408283216493092108,
    2577794401090299805723177598637436117371525412262771825236813936115237585602114357696686099541164980249580094089526387369627399445447896464668107355247993148990034255262021717192029828447047736912032562575292618672346226630177737,
    9097092753543027532933159793556144814276134227405286080166556624316657274280165256861623248902541076900039285592392074751617153907616670295765377162951858063712964557527212039482031296350052367350738141716598584719951567052177519,
    8174235910244322855637254130843352735528509191186418212056519911128301630950848710182451421471531481098828227735010211554839205099309290314993113489826162548089590990963249899714956197889959999884447438378454452096405595048394416,
    2823506900640363315693941780283568096117331722098156706833610340919194199647098542170689133810904702849664199290565773405646243449194786656181872671323095023235608799444864036190997987871160063941897196360905342203429250068859314,
    4625135637721297092934166648990860031642126233341589454312760229225192256970211899532356300747405146834048765116081788846632527090729839758895834854075755594692611781829177188955301784020596520269704429107749955107365380494152652,
]

# Known plaintext prefix (exactly 20 bytes, i.e., first two 10-byte blocks)
KNOWN_PREFIX = b"good luck lmao ictf{"

# Utilities

def split_blocks(b: bytes, block_size: int = 10):
    return [b[i:i+block_size] for i in range(0, len(b), block_size)]

# Discrete log in 2-power order subgroup: finds x s.t. g^x == h (mod m)
# Assumes order(g) = 2^n for some n; returns (x, n)

def dlog_pow2(g: int, h: int, m: int):
    # Find n s.t. g^(2^n) == 1
    n = 0
    t = g % m
    # To avoid infinite loops, cap n reasonably; 4096 bits should suffice for typical moduli
    MAX_N = 4096
    while n < MAX_N:
        t = pow(t, 2, m)
        n += 1
        if t == 1:
            break
    else:
        raise ValueError("g does not appear to have 2-power order within cap")

    # Precompute g2[i] = g^(2^i)
    g2 = [g % m]
    for i in range(1, n):
        g2.append(pow(g2[-1], 2, m))

    # Element of order 2
    T2 = g2[n-1]

    # Recover bits of x from LSB to MSB
    x = 0
    cur = h % m
    for i in range(n):
        # Test if current exponent's LSB is 0 or 1 by raising to 2^(n-1-i)
        t = pow(cur, 1 << (n-1-i), m)
        if t == 1:
            bit = 0
        elif t == T2:
            bit = 1
            # Remove this bit: divide by g^(2^i)
            inv = pow(g2[i], -1, m)
            cur = (cur * inv) % m
        else:
            raise ValueError("Element not in subgroup generated by g (unexpected)")
        x |= (bit << i)
    return x, n


def main():
    # Build known plaintext blocks
    blocks = split_blocks(KNOWN_PREFIX, 10)
    assert len(blocks) == 2
    pt0 = bytes_to_long(blocks[0])
    pt1 = bytes_to_long(blocks[1])

    # Recover keystream for first two blocks
    k0 = CT[0] ^ pt0
    k1 = CT[1] ^ pt1

    # Work in subgroup generated by g = B^(2^16)
    g = pow(B, 1 << 16, m)

    # Compute discrete logs s_high0, s_high1 and subgroup size 2^n
    s_high0, n = dlog_pow2(g, k0, m)
    s_high1, n2 = dlog_pow2(g, k1, m)
    assert n == n2

    # Verify A^(2^n * 2^16) == 1 to ensure we can reduce exponent modulo 2^n
    A16 = pow(A, 1 << 16, m)
    if pow(A16, 1 << n, m) != 1:
        # Not strictly necessary, but warn
        pass

    # Precompute A16^s_high0
    Ahigh = pow(A16, s_high0, m)

    # Precompute A^low for low in 0..65535
    # Using fast doubling via pow with small exponents is fine
    A_low_table = [1] * 65536
    for low in range(1, 65536):
        A_low_table[low] = (A_low_table[low-1] * A) % m

    # Bruteforce low 16 bits of initial state
    target_low_bits_mask = (1 << n) - 1
    found_low = None
    for low in range(65536):
        Aval = (Ahigh * A_low_table[low]) % m
        Y = Aval ^ B
        s1 = pow(Y, e, m)
        s1_high_mod = (s1 >> 16) & target_low_bits_mask
        if s1_high_mod == s_high1:
            found_low = low
            break

    if found_low is None:
        raise RuntimeError("Failed to find low 16 bits of state")

    # Reconstruct initial state modulo 2^n*2^16 (sufficient for all ops below)
    s0 = (s_high0 << 16) | found_low

    # Generate keystreams and decrypt all blocks
    state = s0
    plaintext_chunks = []
    for ct in CT:
        # Keystream
        E = state - (state & 0xffff)
        ks = pow(B, E, m)
        # Decrypt chunk
        pt_chunk_int = ct ^ ks
        plaintext_chunks.append(pt_chunk_int)
        # Update state
        Aval = pow(A, state, m)
        Y = Aval ^ B
        state = pow(Y, e, m)

    # Convert chunks back to bytes
    out = b""
    for x in plaintext_chunks:
        # Each except maybe last is 10 bytes
        b = long_to_bytes(x)
        if len(b) < 10:
            b = (b"\x00" * (10 - len(b))) + b
        out += b

    # Strip potential leading zeros from the last chunk due to padding issues
    print(out)

if __name__ == "__main__":
    main()
